# -- baseurl
# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
# Include trailing slash
baseurl = "https://nitya.dev/"  

# -- title
# title = "Nitya Narasimhan, PhD"  
# Edit directly from config/_default/languages.toml 
# alternatively, uncomment this and remove `title` entry from the aforemention file.

# -- copyright
# -- Seems to get this from somewhere else 
# copyright = "Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved."

# -- set build target directory
publishdir = "../docs" 



# canonifyurls = true
paginate = 3
theme = "hugo-clarity"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
