
[en]
  title = "Nitya Narasimhan"
  LanguageName = "English"
  weight = 1

# -- Comment out and customize below
# -- If you want to see/support localized content options
# [pt]
#  title = "Claridade" # just for the sake of showing this is possible
#  LanguageName = "Português"
#  weight = 2
  