[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Projects"
  identifier = "Project"
  weight = -108
[[main]]
  parent = "Overview"
  name = "Visual Green Tech"
  url = "/projects"
  weight = -10
[[main]]
  parent = "Project"
  name = "Visual Green Tech"
  url = "https://sketchthedocs.dev/visual-green-tech"
  weight = -9
[[main]]
  parent = "Project"
  name = "A-B-See"
  url = "https://sketchthedocs.dev/a-b-see"
  weight = -8

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Vitae"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "Presentations"
  url = "/talks"
  weight = -10
[[main]]
  parent = "Links"
  name = "Publications"
  url = "/pubs"
  weight = -9
[[main]]
  parent = "Links"
  name = "Patents"
  url = "/patents"
  weight = -8
[[main]]
  parent = "Links"
  name = "Community"
  url = "/community"
  weight = -7

[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/nitya"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/nitya"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/nityan"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"